'use strict';

// Builds the bibles/ folder that ships next to "Bible Song Pro panel.html".
//
// Why JS wrappers instead of plain .xml: the control panel runs as an OBS custom
// browser dock over file://, where fetch()/XHR of a sibling file is blocked by the
// browser. A <script> tag is not, so each bible is wrapped in a one-line register
// call and pulled in with a script tag. The panel then hands the XML to its normal
// parseBible() path.
//
// Usage:
//   node scripts/build-bibles.js                 # rebuild from bibles/source/*.xml
//   node scripts/build-bibles.js path/to/ESV.xml # add a bible, then rebuild
//
// Drop your own XML bible into bibles/source/ (or pass it on the command line),
// re-run this, and it shows up in the panel's version bar on next launch.

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.join(__dirname, '..');
const BIBLES_DIR = path.join(REPO_ROOT, 'bibles');
const SOURCE_DIR = path.join(BIBLES_DIR, 'source');

function ensureDirs() {
  fs.mkdirSync(SOURCE_DIR, { recursive: true });
}

// Any XML passed on the command line is copied into bibles/source/ first.
function adoptCliInputs() {
  const inputs = process.argv.slice(2);
  for (const input of inputs) {
    const src = path.resolve(input);
    if (!fs.existsSync(src)) {
      console.error(`skip: ${input} does not exist`);
      continue;
    }
    const dest = path.join(SOURCE_DIR, path.basename(src));
    if (path.resolve(dest) !== src) {
      fs.copyFileSync(src, dest);
      console.log(`added ${path.basename(src)} to bibles/source/`);
    }
  }
}

function build() {
  const sources = fs.readdirSync(SOURCE_DIR)
    .filter(name => name.toLowerCase().endsWith('.xml'))
    .sort();

  if (!sources.length) {
    console.error('No XML bibles found in bibles/source/. Nothing to build.');
    process.exit(1);
  }

  const versions = [];
  for (const fileName of sources) {
    const version = path.basename(fileName, path.extname(fileName));
    const xmlText = fs.readFileSync(path.join(SOURCE_DIR, fileName), 'utf8');

    // JSON.stringify gives us a safely escaped JS string literal for any XML text.
    const wrapped = `window.BSP_REGISTER_BUNDLED_BIBLE(${JSON.stringify(version)}, ${JSON.stringify(xmlText)});\n`;
    const outPath = path.join(BIBLES_DIR, `${version}.js`);
    fs.writeFileSync(outPath, wrapped, 'utf8');

    versions.push(version);
    const mb = (fs.statSync(outPath).size / (1024 * 1024)).toFixed(1);
    console.log(`built bibles/${version}.js (${mb} MB)`);
  }

  // A folder cannot be listed over file://, so the panel needs a manifest naming the versions.
  const manifest = [
    '// Generated by scripts/build-bibles.js — do not edit by hand.',
    `window.BSP_BUNDLED_BIBLES = ${JSON.stringify(versions)};`,
    ''
  ].join('\n');
  fs.writeFileSync(path.join(BIBLES_DIR, 'manifest.js'), manifest, 'utf8');
  console.log(`built bibles/manifest.js -> ${versions.join(', ')}`);
}

ensureDirs();
adoptCliInputs();
build();
